### ISSUE TITLE
Evaluation on ImageNet

### ISSUE THREAD

**Issue by Hayoung93** [decile-team/cords#35]
Hello, thanks for a very interesting and useful project.

Could you mind providing an evaluation method for ImageNet?
I tried to, adding loader for ImageNet to `custom_dataset.py`, but failed due to a GPU memory issue during subset selection.

Many thanks!

**Comment by krishnatejakk** [comment]
@Hayoung93  Sorry for the delay. I will add the notebook for ImageNet evaluation shortly in examples.
