### ISSUE TITLE
Can't install on MACOS

### ISSUE THREAD

**Issue by victor-ribeiro** [decile-team/cords#93]
I'm trying to install CORDS on macOS, but there is this dependency conflict. It looks like there is no torchtext==0.10.1 for Mac. Is there any tutorial to make it work on macOS?

**Comment by Parvez-Khan-1** [comment]
@victor-ribeiro curious to know if this issue is resolved and how? I am facing the same issue on Oracle Linux 7.8 with python3.10

```
Collecting cords
  Using cached cords-0.0.3-py3-none-any.whl (144 kB)
  Using cached cords-0.0.2-py3-none-any.whl (121 kB)
  Using cached cords-0.0.1-py3-none-any.whl (115 kB)
ERROR: Cannot install cords==0.0.1, cords==0.0.2, cords==0.0.3 and cords==0.0.4 because these package versions have conflicting dependencies.
```
